import os

print("88. Merge Sorted Array:", 'tasks/1/solution.py')
print("27. Remove Element", 'tasks/3/solution3.py')
print("26. Remove Duplicates from Sorted Array", 'tasks/3/solution.py')
print("80. Remove Duplicates from Sorted Array II", 'tasks/3/solution2.py')
print("169. Majority Element", 'tasks/2/solution.py')
print("189. Rotate Array", 'tasks/2/solution2.py')
print("125. Valid Palindrome", 'tasks/4/solution.py')
print("58. Length of Last Word", 'tasks/4/solution2.py')
print("14. Longest Common Prefix", 'tasks/4/solution3.py')
print("70. Climbing Stairs", 'tasks/5/solution.py')
print("383. Ransom Note", 'tasks/6/solution.py')
print("13. Roman to Integer", 'tasks/6/solution2.py')
print("12. Integer to Roman", 'tasks/6/solution3.py')
print("28. Find the Index of the First Occurrence in a String", 'tasks/6/solution4.py')
print("21. Merge Two Sorted Lists", 'tasks/6/solution5.py')
print("392. Is Subsequence", 'tasks/6/solution6.py')
print("228. Summary Ranges", 'tasks/6/solution7.py')
print("108. Convert Sorted Array to Binary Search Tree", 'tasks/7/solution.py')